########################################################################################################################
# CI Buildkonfiguration für travis.org
#-----------------------------------------------------------------------------------------------------------------------
# \project    Mpjoe
# \file       .travis.yml
# \creation   2015-01-31, Joe Merten
########################################################################################################################

language: java
jdk: oraclejdk7
env:
  # Achtung ANDROID_HOME muss zu travis-setup-android.sh passen!
  - ANDROID_HOME=$PWD/tmp/android-sdk-linux PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
#    - ANDROID_TARGET=android-19
#    - ANDROID_ABI=armeabi-v7a
before_install:
  - cd Ci && ./travis-setup-android.sh && cd ..
install:
  - cd Ci && ./travis-build.sh && cd ..
before_test:
  - echo "Nichts zu tun für before_test"
script:
  - cd Ci && ./travis-test.sh && cd ..
